### PR TITLE
Fix sum calculation that generates 0 rates

### PR DESCRIPTION
**Pull request by dcorbacho**
Closes https://github.com/rabbitmq/rabbitmq-management/issues/352

### CODE REVIEW

**Comment by michaelklishin** [comment]
When I run

    bin/runjava com.rabbitmq.perf.PerfTest -x 1 -y 0 -f persistent -u "flood-qa"

and wait for maybe 5-15 minutes, I see that on individual queue page the chart looks like this:

Alt text

It then does not get out of this state in the 5 minutes I waited. I will check if resetting stats on the node helps (it should but just as a data point).

**Comment by michaelklishin** [comment]
To clarify: I had a publisher online hammering away at 15K/second at the time the screenshot was taken.

We have seen this particular chart state before with @gerhard, so this may or may not be a novel issue with this PR.

FWIW I cannot reproduce the original issue with publishing rate dropping to 0 for a moment every so often.

**Comment by michaelklishin** [comment]
More observations on the above: refreshing the page does not help but once more than a minute passes (the interval used by charts by default), the spike on the left clears.

**Comment by michaelklishin** [comment]
On a long enough run with just consumers the above also affects delivery rates:

Alt text

**Comment by dcorbacho** [comment]
@michaelklishin that weird chart can also be reproduced in stable

**Comment by michaelklishin** [comment]
With a034ed87fc6437eb8c48ced375cbea67c9b35ab6 I can no longer reproduce the above issue or #352 👍 .

**Pull request merged**
